version: '3.8'

services:
  postgres:
    image: groonga/pgroonga:alpine-3.1.8-postgres-17
    platform: linux/amd64  # Required for Apple Silicon compatibility
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: pgdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: