openapi: 3.0.1
info:
  title: Tilawah app
  description: Tialwah app
  license:
    name: <TBD>
  version: 0.0.1
servers:
  - url: http://Tialwahapp.com
paths:
  /users:
    $ref: ./paths/users.yaml
  /users/{user_uuid}:
    $ref: ./paths/user_uuid.yaml
  /auth/login:
    $ref: ./paths/auth_login.yaml
  /auth/refresh:
    $ref: ./paths/auth_refresh.yaml
